# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02d95b302fb483751e5409e1bb79b15d60b6f3f05ac03fe3ae1dbb878455c254f9daf324ea86385b5975bbba7fc3c9c8c30334313052cdac11fb42e8bc4c5ee6

test:
  secret_key_base: 8e67a78cf38d20ead43b75659d119758581dc1d66824664427cf609939cc8edf0365fb15feba6473de2541ed2ae9b2f385d7855b4fb7421c5637f38c8f721560

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
